version: '3.9'

services:
  database:
    image: postgres:13.15
    container_name: database-1
    stop_signal: SIGKILL
    restart: always
    env_file:
      - '.env'
    ports:
      - '${PG_PORT}:5432'
    volumes:
      - ./database/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_NAME}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d ${PG_NAME} -U ${PG_USER}']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server-1
    stop_signal: SIGKILL
    restart: always
    command: ["gunicorn", "--pythonpath", ".", "wallet_project.wsgi:application", "--bind", "0.0.0.0:8000"]
    env_file:
      - '.env'
    ports:
      - '8000:8000'
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://0.0.0.0:8000/admin/ || exit 1']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    links:
      - database
    depends_on:
      database:
        condition: service_healthy